### ISSUE TITLE
Boost hot water service not working

### ISSUE THREAD

**Issue by gbolton2008** [asantaga/wiserHomeAssistantPlatform#313]
When calling from developer tools and unknown error occurs, when calling from a script an error is thrown if a hub isn't selected (I only have a single hub), and when a hub is selected error 'WiserUpdateCoordinator' object has no attribute 'async_update'

Error is present in v3.2.0beta4 and at least 2 previous betas. V3.1.7 works as expected

**Comment by gbolton2008** [comment]
Tested and working fine with 3.2.0 release
