### ISSUE TITLE
Wiser 3.4.20 fails to load on Home Assistant 2026.7.4: cannot import wrap from aiofiles.base

### ISSUE THREAD

**Issue by kjc200763-hue** [asantaga/wiserHomeAssistantPlatform#678]
Wiser: 3.4.20
aioWiserHeatAPI: 1.7.3
Fails on Home Assistant Core: 2026.7.4
Works on Home Assistant Core: 2026.7.3
Python: 3.14

ImportError: cannot import name 'wrap' from 'aiofiles.base'
(/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

**Comment by scooper1** [comment]
i had this  issue and use the openai add-in to fix the issue.   i think it indicated that  manifest file was missing a dependency - it said that issue is like to come back on next  update.   running 2026.8 beta

**Comment by asantaga** [comment]
I'll need to test this tomorrow (away from home ATM), which manifest file was missing a dependency? the one in ths integration or the aioWiserHeatAPI?

**Comment by scooper1** [comment]
Sorry not sure as it fixed after about the 5th try and once fixed and restarted. It tends to delete the logs and used resources  I just remember it recording that it believed it was unloaded resource not set to required by manifest

**Comment by jamieroyston** [comment]
I've had this issue. 
---

Confirming on a separate instance, later HA version:

- Wiser: 3.4.20
- Home Assistant Core: 2026.8.0
- Python: 3.14

```
ImportError: cannot import name 'wrap' from 'aiofiles.base'
```

Same root cause — `aioWiserHeatAPI`'s `setup.py` pins only `aiofiles>=23.2.1`, no upper bound, so it picks up whatever `aiofiles` HA Core bundles. Now confirmed on both 2026.7.4 and 2026.8.0, suggesting this hits whenever HA's bundled `aiofiles` crosses whatever version dropped `wrap`, not a one-off regression in a single HA release.

**Comment by jamieroyston** [comment]
> I'll need to test this tomorrow (away from home ATM), which manifest file was missing a dependency? the one in ths integration or the aioWiserHeatAPI?

Believe it's the latter.

**Comment by asantaga** [comment]
@msp1974 Mark is this something you can look at in aioWiserAPI. Looks like they dropped the wrap parameter

**Comment by asantaga** [comment]
Cant reproduce this in my dev or prod environment.. 
Im running wiser 3.4.20, HA core 2026.8.0, aiofiles 25.1.0 and aioWiserHeatAPI 1.7.3

weird

**Comment by asantaga** [comment]
ok Ive tried this on a different container where Im running aiofiles 24.1.0 and it also works. Using some AI it thinks its a corrupted/mismatched multiple versions of aiofiles installed. 

Run this command

If you run native HA
`python3 -c "import aiofiles, aiofiles.base, importlib.metadata as m; print('aiofiles:', m.version('aiofiles')); print('aioWiserHeatAPI:', m.version('aioWiserHeatAPI')); print('aiofiles path:', aiofiles.__file__); print('base path:', aiofiles.base.__file__); print('base.wrap:', hasattr(aiofiles.base, 'wrap')); import aiofiles.os; print('aiofiles.os: OK'); print('os path:', aiofiles.os.__file__)"
`
If you run within a docker container (Change the container name)

`docker exec -it homeassistant python3 -c "import aiofiles, aiofiles.base, importlib.metadata as m; print('aiofiles:', m.version('aiofiles')); print('aioWiserHeatAPI:', m.version('aioWiserHeatAPI')); print('aiofiles path:', aiofiles.__file__); print('base path:', aiofiles.base.__file__); print('base.wrap:', hasattr(aiofiles.base, 'wrap')); import aiofiles.os; print('aiofiles.os: OK'); print('os path:', aiofiles.os.__file__)"
`

if you are running HASS, 

- Install the Terminal & SSH or Advanced SSH & Web Terminal add-on.
- Disable the add-on’s Protection mode so it can access Docker.
- Open its terminal and run:
`docker exec -it homeassistant python3 -c "import aiofiles, aiofiles.base, importlib.metadata as m; print('aiofiles:', m.version('aiofiles')); print('aioWiserHeatAPI:', m.version('aioWiserHeatAPI')); print('aiofiles path:', aiofiles.__file__); print('base path:', aiofiles.base.__file__); print('base.wrap:', hasattr(aiofiles.base, 'wrap')); import aiofiles.os; print('aiofiles.os: OK'); print('os path:', aiofiles.os.__file__)"
`

**Comment by rossburton** [comment]
FWIW, I just had this after upgrading to haos 2026.8.1 but interestingly a proper reboot of the VM solved it.

**Comment by asantaga** [comment]
it feels like a multiple copies of aiofiles mismatch but i honestly have no idea..

**Comment by msp1974** [comment]
Im looking at this as i saw this upgrading to 2026.8 but a further reboot fixed it.  I just upgraded to 2026.8.1 and it is showing the same error again.

HA pins aiofiles v24.1.0 but there is a change in dev to up this to 25.0.1.  

We dont set the upper bound due to HA pinning the version so we have to use whatever they set.

I am also seeing the same error failing to load alexa media player.

So, i agree with @asantaga that this has the whiff of a version conflict somewhere and maybe 25.1.0 has a breaking change as 24.1.0 has been around for a while now and something is pinning that version in conflict to HA.

**Comment by msp1974** [comment]
Adding error for ref

```
Logger: homeassistant
Source: config_entries.py:4192
First occurred: 08:37:29 (2 occurrences)
Last logged: 08:40:00

Error doing job: Task exception was never retrieved (task: None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4185, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1124, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1202, in async_get_platforms
    import_future.result()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1190, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1114, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1289, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1321, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 201, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1314, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1406, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 759, in exec_module
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
  File "/config/custom_components/wiser/__init__.py", line 32, in <module>
    from .coordinator import WiserUpdateCoordinator
  File "/config/custom_components/wiser/coordinator.py", line 8, in <module>
    from aioWiserHeatAPI.wiserhub import (
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/wiserhub.py", line 44, in <module>
    from .devices import _WiserDeviceCollection
  File "/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/devices.py", line 8, in <module>
    from .binary_sensor import (
    ...<2 lines>...
    )
  File "/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/binary_sensor.py", line 10, in <module>
    from .helpers.device import _WiserDevice
  File "/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/helpers/device.py", line 14, in <module>
    from ..helpers.misc import is_value_in_list
  File "/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/helpers/misc.py", line 1, in <module>
    import aiofiles.os as os
  File "/usr/local/lib/python3.14/site-packages/aiofiles/os.py", line 5, in <module>
    from . import ospath as path
  File "/usr/local/lib/python3.14/site-packages/aiofiles/ospath.py", line 5, in <module>
    from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 133, in _async_start
    await gather_with_limited_concurrency(FLOW_INIT_LIMIT, *init_coros)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 111, in gather_with_limited_concurrency
    return await gather(
           ^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 109, in sem_task
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1549, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1603, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1854, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.hass, handler_key, self._hass_config
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4206, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 4192, in _load_integration
    raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler
```

**Comment by msp1974** [comment]
Having looked at this, it does look like HA is maybe installing 25.0.1 and although in the requirements_all.txt file is pinned to 24.1.0, in package_contraints is is >=24.1.0.  Where package_contraints is called first.

Looking at the changes to this version, it moves the wrap function to a different file but aiofiles is basically this wrap function around the actual python functions and nothing else and should work (in fact I will test a proper upgrade to that version and report back).

So, in order to get back to the HA pinned version and fix this error, you need to do the following to get the right version.

Use the terminal addin.

on the command line type
```docker exec -it homeassistant bash```

this will take you into the actual homeassistant container.

In here remove and readd the pinned version.  If you want to see what version you currently have first use ```pip show aiofiles```
```
pip install aiofiles==24.1.0
exit
```

Now restart HA.  This does not seem to install 25.1.0 again as it does meet all the criteria.  IDK.

***NOTE:***  Installing 25.1.0 (other than the conflict error for alexapy when installing) also works, so something has clearly got screwy.  But enforces this is not a specific wiser integration issue other than the fact we use that library.  It maybe a conflict in the HA requirements files.

**Comment by msp1974** [comment]
Tracking this HA issue - https://github.com/home-assistant/core/issues/178478

**Comment by asantaga** [comment]
agree, I asked claude to analyse one , codex sol said the same,  and it came up with this

```aioWiserHeatAPI 1.7.3 (the dependency your manifest.json pins) uses aiofiles.open() normally in schedule.py — that's the public, stable API, not the internal wrap helper. So this isn't a bug in your integration or in msp1974's API code calling something deprecated.

The wrap function has historically lived in aiofiles.base, but newer aiofiles releases moved/renamed it (it now shows up under aiofiles.os). aioWiserHeatAPI's setup.py pins aiofiles>=23.2.1 with no upper bound, so if HA 2026.7.4 pulled in a newer aiofiles release as a transitive dependency (I checked the HA 2026.7 changelog — no explicit aiofiles bump mentioned, so it's likely transitive), something else in that Python 3.14 environment that still does from aiofiles.base import wrap — could be a leftover/mismatched aiofiles install, or another HA-side dependency — breaks at import time.

Practical read: this is very likely an aiofiles version-skew issue triggered by Python 3.14 + a newer aiofiles pulled in during the 2026.7.4 update, not something wrong in your Wiser code. Worth asking the reporter for the full traceback (which line, which module does from aiofiles.base import wrap) and their pip show aiofiles version — that'll confirm whether it's a stale/duplicate aiofiles install or a genuine incompatibility that needs an upper-bound pin added to aioWiserHeatAPI's aiofiles>=23.2.1 requirement.
```

Sounds like something outside of our control

**Comment by jamieroyston** [comment]
I have just noticed on my next update of HA core 2026.8.1, that this issue has solved itself. Thanks for your help though, it's an awesome integration.

**Comment by plord12** [comment]
> I have just noticed on my next update of HA core 2026.8.1, that this issue has solved itself. Thanks for your help though, it's an awesome integration.

Still broken for me on 2026.8.1 

(although having said that, although I see the error in the logs, the integration did start)

**Comment by asantaga** [comment]
if the integration still starts is it still broken?

Its weird, i honestly not sure how to fix it..

**Comment by asantaga** [comment]
From the thread here, and other threads one workaround/solution is to reboot the container/HA. Is this working for others? As @msp1974 has mentioned further up in the thread, this looks like a HA issue..

**Comment by elastic-paul** [comment]
> From the thread here, and other threads one workaround/solution is to reboot the container/HA. Is this working for others? As [@msp1974](https://github.com/msp1974) has mentioned further up in the thread, this looks like a HA issue..

A "ha host reboot" fixed for me. Thanks

**Comment by asantaga** [comment]
feels like this a HA thing, workaround, reboot HA host...

will leave open for now

**Comment by vaderag** [comment]
I just got this issue but only after updating to 2026.9.2

> Setup failed for custom integration 'wiser': Unable to import component: cannot import name 'wrap' from 'aiofiles.base' (/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

**Comment by asantaga** [comment]
for the network issue see issue #702 , it appears to be a HA thing
