### ISSUE TITLE
"CalculatedTemperature" & errors when no TRV in a room

### ISSUE THREAD

**Issue by angrycamel** [asantaga/wiserHomeAssistantPlatform#10]
Hi - thanks for this component. All the important stuff is working really well :+1: 

The errors below recur every minute or so. I wonder if it is because I have set up some rooms which do not have devices in yet (my order for more TRVs hasn't arrived yet!). Just a thought

I'm using Home Assistant 0.84.6 and a Wiser HeatHubR (single zone). I also see the HotWater errors there's an open issue for.

```
2019-01-03 22:00:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 225, in state_attributes
    self.hass, self.current_temperature, self.temperature_unit,
  File "/config/custom_components/climate/wiser.py", line 73, in current_temperature
    temp=self.handler.getHubData().getRoom(self.roomId).get("CalculatedTemperature")/10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-01-03 22:00:46 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 239, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 225, in state_attributes
    self.hass, self.current_temperature, self.temperature_unit,
  File "/config/custom_components/climate/wiser.py", line 73, in current_temperature
    temp=self.handler.getHubData().getRoom(self.roomId).get("CalculatedTemperature")/10
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by asantaga** [comment]
Hey there,

Yes the error your seeing is for rooms without a TRV..  @hueytech (a mate of mine) reported the same error.. Its not an issue though, easy workaround is to remove the rooms until you have TRVs.. (is there any point in having rooms without TRVs???)

but I'll still add some guards anyway.. and yes I need to get my finger out and fix the hotwater errors...

**Comment by hueytech** [comment]
Well yes there is a reason to have a room without TRV and that is if you have just a Room Themostat in a Room. I have one in the kitchen that contains a rad that cannot have a TRV attached to it is not independant but when the room is cold the Room Stat asks for heat, but I can ignore the msg still ;-)

**Comment by djashjones** [comment]
Got some TRV's fitted finally and my stat is in the dining room and all my TRV's are upstairs.

**Comment by asantaga** [comment]
can u check if this is still an error with the latest HACS release today

**Comment by djashjones** [comment]
No HACS update for me just yet

**Comment by mrvladis** [comment]
Hi both,

I have just installed 1.8 from HASC.

Funny enough had to restart the whole container, as just restarting HA from the server control didn't work.
But now it loads well, without any errors and I can see the climate devices appeared within the HA.

Thanks.

**Comment by djashjones** [comment]
I'm getting a config error:

Component error: wiser - cannot import name 'TEMP_MINIMUM' from 'wiserHeatingAPI.wiserHub' (/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py)

wiser:
  host: 192.168.1.218
  password: !secret wiser_pwd
  scan_interval: 300
  minimum: -5
  boost_temp: 20
  boost_time: 30

**Comment by mrvladis** [comment]
@djashjones  do you have v1.8 installed?

Also, how do you run you HA? Hassio / Hasbian / Docker?

**Comment by djashjones** [comment]
My HA install is HASSIO in a docker under ubuntu.

Gone back to 1.7.1

**Comment by mrvladis** [comment]
Did you restart your container after upgrade to 1.8? Not just HA, but whole container?

**Comment by djashjones** [comment]
Well I just rebooted my PC after reading your comment earlier.

**Comment by mrvladis** [comment]
That's strange. 
In my case - I have home assistant 103.0 in docker. May be hassio makes a difference.

What version you on?

Thanks.

**Comment by djashjones** [comment]
103.6.

Is is weird that it works for you but not for me. Got to be something silly.

**Comment by mrvladis** [comment]
may be something cached somewhere. 

Can you may be try to completely uninstall 1.7.
Restart container.
Install 1.8 
Restart Container?

**Comment by djashjones** [comment]
Same issue but when I went to install it. It installs 1.7.1 by default and not 1.8.

**Comment by msp1974** [comment]
I think this is also a problem with the manifest.json file.  Included correct version in PR that also fixes the original issue here.

**Comment by msp1974** [comment]
> I'm getting a config error:
> 
> Component error: wiser - cannot import name 'TEMP_MINIMUM' from 'wiserHeatingAPI.wiserHub' (/usr/local/lib/python3.7/site-packages/wiserHeatingAPI/wiserHub.py)
> 
> wiser:
> host: 192.168.1.218
> password: !secret wiser_pwd
> scan_interval: 300
> minimum: -5
> boost_temp: 20
> boost_time: 30

You also need to set your boost_temp value to something more like 2 (this was a breaking change in previous version

**Comment by djashjones** [comment]
Yes, I noticed the boost_temp. So shall I wait for the merge before updating or update now?

**Comment by msp1974** [comment]
You can update api manually now if you want and then use v1.8 of the HACs component. The fix for rooms with only thermostats and no trvs is in 1.8. The merge awaiting is if you have a room with no trv or thermostat.

**Comment by djashjones** [comment]
Hooray, it's working now. No more errors. This issue can be closed now. Great work!!!

**Comment by asantaga** [comment]
Good stuff, thanks
