### ISSUE TITLE
Issue when upgrading to 3.4.13

### ISSUE THREAD

**Issue by dmelliott20** [asantaga/wiserHomeAssistantPlatform#539]
integration fails to load with the following error - rollback to 3.4.12 restores things fine

Logger: homeassistant.config_entries
Source: config_entries.py:635
First occurred: 6:33:52 PM (1 occurrences)
Last logged: 6:33:52 PM

Error setting up entry WiserHeat03C0BB for wiser
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiser/__init__.py", line 104, in async_setup_entry
    coordinator = WiserUpdateCoordinator(hass, config_entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/wiser/coordinator.py", line 143, in __init__
    ).get(CONF_AUTOMATIONS_HW_SENSOR_ENTITY_ID)
      ^^^
AttributeError: 'bool' object has no attribute 'get'

**Comment by msp1974** [comment]
Are you able to remove and readd.  I needed to get the config options updated to change all the things to make it work better.  Seems there maybe some issue in the migration of these, but if you remove the integration, update it in HACs and add back, it should work fine.  Just then need to setup hw climate again.

**Comment by dmelliott20** [comment]
Will give it a try later on - thanks.

**Comment by s1mpleman** [comment]
Will attempt too as I hadn't tried that this morning

**Comment by floringheorghita** [comment]
I have tried readding the plugin and still got the same error.

**Comment by ExplosiveDad** [comment]
Same error for me after an update this morning.

**Comment by Chaoscontrol** [comment]
Same here. Sorry, too afraid to remove integration as I don't want to lose or get different entity names (not sure if I ever changed them from default). I have too many templates and helpers with these.

**Comment by ExplosiveDad** [comment]
> Same here. Sorry, too afraid to remove integration as I don't want to lose or get different entity names (not sure if I ever changed them from default). I have too many templates and helpers with these.

I also had my finger on the remove button and bottled it 😊. Rolled back to 3.4.12 for now until fixed and all is back to normal.

**Comment by Chaoscontrol** [comment]
> > Same here. Sorry, too afraid to remove integration as I don't want to lose or get different entity names (not sure if I ever changed them from default). I have too many templates and helpers with these.
> 
> I also had my finger on the remove button and bottled it 😊. Rolled back to 3.4.12 for now until fixed and all is back to normal.

To rollback, do you just redownload from HACS choosing prev version?

**Comment by ExplosiveDad** [comment]
> > > Same here. Sorry, too afraid to remove integration as I don't want to lose or get different entity names (not sure if I ever changed them from default). I have too many templates and helpers with these.
> > 
> > 
> > I also had my finger on the remove button and bottled it 😊. Rolled back to 3.4.12 for now until fixed and all is back to normal.
> 
> To rollback, do you just redownload from HACS choosing prev version?

Yea, exactly 👍

**Comment by msp1974** [comment]
So, are you all using the hw climate automation?

**Comment by ExplosiveDad** [comment]
> So, are you all using the hw climate automation?

I dont use anything for HW only Heating.

**Comment by s1mpleman** [comment]
> So, are you all using the hw climate automation?

I am yeah, rolling back to .12 broke it for me. The entity is unavailable.

**Comment by msp1974** [comment]
Ok, so been looking at this to work out what is going on.

So, as said above, in this version there is a change in how we a re storing the config options and therefore have a migration routine to move from the current v1.1 format to a new v1.2 format.

It seems that in some cases, it is failing to migrate and therefore you see this error.

I think in each case it is that you have previously enabled either passive mode or hw climate automation in the config options but have then subsequently disabled it.  Therefore, I think my advice to remove and readd, still stands and will fix it.

I am working on a software fix so you don't have to remove and readd that should be out later today, but if you are desperate....go with original advice.

@floringheorghita are you sure you removed and readded?  Or are you sure you are getting the same error?

**Comment by msp1974** [comment]
OK, v3.4.14 now released that should fix this issue.

**Comment by ExplosiveDad** [comment]
> OK, v3.4.14 now released that should fix this issue.

Thanks for the quick turn around. Downloaded and on reboot the integration has set itself up, without doing any in depth checks, my dashboards are working okay so happy days. Thanks

**Comment by dmelliott20** [comment]
thanks, 3.4.14 confirmed working ok for me

**Comment by msp1974** [comment]
Thanks all for prompt feedback.  Will close issue now.

**Comment by rnorth** [comment]
Bizarrely this issue (or something very similar) is occurring for me with _3.4.14_:
```
default=options.get(CONF_AUTOMATIONS_HW_CLIMATE, {}).get(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'bool' object has no attribute 'get'
```

Additionally, when entering the integration configuration and choosing automation parameters, I'm met with a dialog that just says 'Error'.

Downgrading to 3.4.12 has everything working for now.

Due to an unrelated problem mentioned in [this message](https://community.home-assistant.io/t/drayton-wiser-home-assistant-integration/80965/4035) I had previously upgraded to 3.4.13, back down to 3.4.12 and then tried upgrading to 3.4.14 - I'm not sure if this could have put my configuration into a state where the integration can't ingest it.

What would you advise I do? I'd be happy to raise a new issue if you'd like.

**Comment by msp1974** [comment]
If you are happy to remove and readd the config, then you can upgrade to 3.4.14, remove your hub from the integration and add it again.

If you're not happy to do that then you could find the config entry in core.config_entries in .storage directory and remove the options config to make it just options={}.

Or if not, send me the whole config entry line (you can obfuscate your secret key) and I'll have a look.

**Comment by rnorth** [comment]
Thank you - I'll attempt the .storage edit and see how it goes!
