### ISSUE TITLE
Integration fails to load on HA 2026.8 / Python 3.14 - cannot import name 'wrap' from aiofiles.base

### ISSUE THREAD

**Issue by elastic-paul** [asantaga/wiserHomeAssistantPlatform#688]
After upgrading Home Assistant to 2026.8, the Wiser integration no longer loads.

The integration was working before the upgrade. It now fails during import, before attempting to communicate with the Wiser Hub.

Error

Setup failed for custom integration 'wiser': Unable to import component:
cannot import name 'wrap' from 'aiofiles.base'
(/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

The traceback shows the failure occurs through aioWiserHeatAPI:

/config/custom_components/wiser/__init__.py
  from .coordinator import WiserUpdateCoordinator
/config/custom_components/wiser/coordinator.py
  from aioWiserHeatAPI.wiserhub import ...
/usr/local/lib/python3.14/site-packages/aioWiserHeatAPI/helpers/misc.py
  import aiofiles.os as os
/usr/local/lib/python3.14/site-packages/aiofiles/os.py
  from .base import wrap
ImportError: cannot import name 'wrap' from 'aiofiles.base'

The Wiser config flow also fails with:

Error occurred loading flow for integration wiser:
cannot import name 'wrap' from 'aiofiles.base'
(/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

Environment

* Home Assistant: 2026.8.x
* Python: 3.14
* Integration: Drayton Wiser Integration for Home Assistant
* Installation: Custom integration

Additional information

This appears to be a dependency compatibility issue involving aioWiserHeatAPI and the version of aiofiles included in the current Home Assistant environment.

aioWiserHeatAPI/helpers/misc.py imports:

import aiofiles.os as os

which results in aiofiles/os.py attempting:

from .base import wrap

This then fails because wrap cannot be imported from aiofiles.base.

As a result, the Wiser integration fails during initial import and never reaches the point of communicating with the Wiser Hub.

Full relevant exception:

ImportError: cannot import name 'wrap' from 'aiofiles.base'
(/usr/local/lib/python3.14/site-packages/aiofiles/base.py)

**Comment by asantaga** [comment]
Duplicate of this https://github.com/asantaga/wiserHomeAssistantPlatform/issues/678

please see thread
