### ISSUE TITLE
Issue not loading on v3.4.16

### ISSUE THREAD

**Issue by rolandas-valantinas** [asantaga/wiserHomeAssistantPlatform#575]
Upgraded from v3.4.15 and HA has thrown a warning 
```
Detected that custom integration 'wiser' calls `device_registry.async_get_or_create` referencing a non existing `via_device` ('wiser', 'WiserHeat027AB9'), with device info: {'identifiers': {('wiser', 'WiserHeat027AB9 Wiser Study')}, 'manufacturer': 'Drayton Wiser', 'model': 'Room', 'name': 'Wiser Study', 'via_device': ('wiser', 'WiserHeat027AB9')} at custom_components/wiser/climate.py, line 138: async_add_entities(wiser_rooms, True). This will stop working in Home Assistant 2025.12.0, please create a bug report at https://github.com/asantaga/wiserHomeAssistantPlatform/issues
```
This doesn't seem to be problem by itself, but all measurements from dashboard disappeared. Reverting solved the issue.
Please let me know if you want more data

**Comment by msp1974** [comment]
This message is a duplicate of #551 and in itself does not stop HA loading.  Equally, a second reboot removes the warning.

If all your sensors went unavailable, then the integration did not load for some other reason.

Can you review your logs and see what error messages may exist.

**Comment by rolandas-valantinas** [comment]
Thank you. I'll give it a go again tomorrow and see if multiple restarts help. Otherwise will get all the logs

**Comment by yavinmaster** [comment]
I had the same error today after updating from 3.4.15 to 3.4.16.  I was running HA 2025.1.2 in docker but after updating to 2025.3.4 the integration loaded without issue.  For reference, the errors I had are below.

```Logger: homeassistant.config_entries
Source: config_entries.py:3314
First occurred: 12:04:21 (1 occurrences)
Last logged: 12:04:21

Error occurred loading flow for integration wiser: cannot import name 'LovelaceData' from 'homeassistant.components.lovelace' (/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py)```

```Logger: homeassistant.util.loop
Source: util/loop.py:77
First occurred: 12:03:55 (2 occurrences)
Last logged: 12:04:21

Detected blocking call to import_module with args ('custom_components.wiser',) in /usr/src/homeassistant/homeassistant/loader.py, line 1075: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component component = await integration.async_get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component comp = self._get_component() File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component ComponentProtocol, importlib.import_module(self.pkg_path)
Detected blocking call to import_module with args ('custom_components.wiser.config_flow',) in /usr/src/homeassistant/homeassistant/loader.py, line 1304: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 227, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 213, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 154, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 707, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 678, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2033, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/util/async_.py", line 112, in sem_task return await task File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1315, in async_init flow, result = await self._async_init(flow_id, handler, context, data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1340, in _async_init flow = await self.async_create_flow(handler, context=context, data=data) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1536, in async_create_flow handler = await _async_get_flow_handler( File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3333, in _async_get_flow_handler await _load_integration(hass, domain, hass_config) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3312, in _load_integration await integration.async_get_platform("config_flow") File "/usr/src/homeassistant/homeassistant/loader.py", line 1108, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1173, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1098, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1272, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1304, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")```


```Logger: homeassistant.setup
Source: setup.py:334
First occurred: 12:03:55 (1 occurrences)
Last logged: 12:03:55

Setup failed for custom integration 'wiser': Unable to import component: cannot import name 'LovelaceData' from 'homeassistant.components.lovelace' (/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1015, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wiser/__init__.py", line 33, in <module>
    from .frontend import JSModuleRegistration
  File "/config/custom_components/wiser/frontend/__init__.py", line 8, in <module>
    from homeassistant.components.lovelace import LovelaceData
ImportError: cannot import name 'LovelaceData' from 'homeassistant.components.lovelace' (/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1035, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    comp = self._get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/wiser/__init__.py", line 33, in <module>
    from .frontend import JSModuleRegistration
  File "/config/custom_components/wiser/frontend/__init__.py", line 8, in <module>
    from homeassistant.components.lovelace import LovelaceData
ImportError: cannot import name 'LovelaceData' from 'homeassistant.components.lovelace' (/usr/src/homeassistant/homeassistant/components/lovelace/__init__.py)```

**Comment by rolandas-valantinas** [comment]
I've experienced same issue as @yavinmaster initially and can confirm that upgrading to HA 2025.3.4 first and then upgrading Wiser Integration works!

**Comment by rivet-defiance-lament-pomp** [comment]
Just another scenario - I updated to 3.4.16 running on 2025.0/14.1 and recieved the "Not Loaded" status and the logs showed as per the attachment below:

![Image](https://github.com/user-attachments/assets/7cd1003f-ba91-4ea6-876c-5210e3bc0059)

I've just updated to 2025.5.0 and it came straight up. Maybe the dev could update the min HA version? (also just updated core to 15.2 and all is still well)

**Comment by msp1974** [comment]
Yes, I left this issue open to remind me to do that.  Unfortunately, changes in HA force us to update the integration which prevent it being backwards compatible with lower versions of HA.  Will ensure we are clear on min HA version in future.

**Comment by msp1974** [comment]
Updated wiki and dev branch.  Will close this now as will be in next release.
